In [6]:
# Path
import sys
import os
qprc_path = os.path.abspath(os.path.join('..'))
if qprc_path not in sys.path:
    sys.path.append(qprc_path)
import numpy as np
from kernelfuzzy.fuzzyset import FuzzySet
from kernelfuzzy.memberships import gaussmf

# Creating fuzzy sets objects via the FuzzySet Class

## Example 1

Using elements and membership degrees

In [7]:
elements = ["apple", "banana", "cherry"]
membership_degrees = [.1, .5, .1]

X = FuzzySet(elements, membership_degrees=membership_degrees)
X.show()



Fuzzy set: [('apple', 0.1), ('banana', 0.5), ('cherry', 0.1)]


Properties:
(_elements)      
 ['apple', 'banana', 'cherry'] 

(_elements_type) 
 <class 'str'> 

(_membership_function)            
 None 

(_membership_degrees)            
 [0.1, 0.5, 0.1] 

(_membership_function_params)        
 None 



In [8]:
elements = [np.array([2,3]), np.array([4,5]), np.array([3,7])]
membership_degrees = [.1, .5, .1]

X = FuzzySet(elements, membership_degrees=membership_degrees)
X.show()



Fuzzy set: [(array([2, 3]), 0.1), (array([4, 5]), 0.5), (array([3, 7]), 0.1)]


Properties:
(_elements)      
 [array([2, 3]), array([4, 5]), array([3, 7])] 

(_elements_type) 
 <class 'numpy.ndarray'> 

(_membership_function)            
 None 

(_membership_degrees)            
 [0.1, 0.5, 0.1] 

(_membership_function_params)        
 None 



In [9]:
elements = [[2,3], [4,5], [3,7]]
membership_degrees = [.1, .5, .1]

X = FuzzySet(elements, membership_degrees=membership_degrees)
X.show()



Fuzzy set: [([2, 3], 0.1), ([4, 5], 0.5), ([3, 7], 0.1)]


Properties:
(_elements)      
 [[2, 3], [4, 5], [3, 7]] 

(_elements_type) 
 <class 'list'> 

(_membership_function)            
 None 

(_membership_degrees)            
 [0.1, 0.5, 0.1] 

(_membership_function_params)        
 None 



## Example 3

Using elements and Gaussian membership function

In [11]:
elements = np.random.uniform(0, 100, 3)
mf = gaussmf
membership_function_params = [np.mean(elements), np.std(elements)]

X = FuzzySet(elements, membership_function=gaussmf, membership_function_params=membership_function_params)
X.show()



Fuzzy set: [(21.215095457953648, 0.3002527260644268), (37.40730724310275, 0.950787728575753), (66.1104339329819, 0.1743998179709138)]


Properties:
(_elements)      
 [21.21509546 37.40730724 66.11043393] 

(_elements_type) 
 <class 'numpy.float64'> 

(_membership_function)            
 <function gaussmf at 0x109660bf8> 

(_membership_degrees)            
 [0.30025273 0.95078773 0.17439982] 

(_membership_function_params)        
 [41.5776122113461, 18.564148904864172] 



The _FuzzySet_ class supports the membership calculation of multi-dimensional sets. In this example, a 2-dimensional set is used.

In [12]:
covar = np.array([[1, 0], [0, 1]])
mean = np.random.uniform(0, 100, 2)
elements = np.random.multivariate_normal(mean, covar, 10)

X = FuzzySet(elements, membership_function=gaussmf, membership_function_params=[mean, covar])
X.show()




Fuzzy set: [(array([36.17732842, 75.59881084]), 0.043817933317050896), (array([36.42531708, 76.15363013]), 0.08795403940907069), (array([34.86394322, 79.92425214]), 0.0002094682662520307), (array([35.49367622, 77.83874249]), 0.45381612735024357), (array([33.6230402 , 76.51851635]), 0.07898633102300447), (array([36.05591698, 77.84491774]), 0.21837087515284015), (array([32.26926615, 77.98130997]), 0.00011006304492094277), (array([35.15225643, 76.00542267]), 0.35259017344879295), (array([34.15522705, 79.44053465]), 0.0011302993161332836), (array([35.64609631, 77.66582802]), 0.5106413244188857)]


Properties:
(_elements)      
 [[36.17732842 75.59881084]
 [36.42531708 76.15363013]
 [34.86394322 79.92425214]
 [35.49367622 77.83874249]
 [33.6230402  76.51851635]
 [36.05591698 77.84491774]
 [32.26926615 77.98130997]
 [35.15225643 76.00542267]
 [34.15522705 79.44053465]
 [35.64609631 77.66582802]] 

(_elements_type) 
 <class 'numpy.ndarray'> 

(_membership_function)            
 <function ga

# Using Numba TODO

In [16]:
from numba import types

class FuzzySetType(types.Type):
    def __init__(self):
        super(FuzzySetType, self).__init__(name='FuzzySet')

fuzzySet_type = FuzzySetType()

#########################

from numba.extending import typeof_impl

@typeof_impl.register(FuzzySet)
def typeof_index(val, c):
    return fuzzySet_type

#######################

# see this https://numba.pydata.org/numba-doc/latest/extending/interval-example.html